# Generated by Django 3.2.7 on 2021-10-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('admin_name', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('mobile_no', models.PositiveBigIntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('alt_mobile_no', models.PositiveBigIntegerField(blank=True)),
                ('aadhar_no', models.PositiveBigIntegerField(blank=True, unique=True)),
                ('aadhar_image', models.ImageField(blank=True, upload_to='')),
                ('email_id', models.EmailField(blank=True, max_length=254, unique=True)),
                ('status', models.CharField(choices=[('verified', True), ('unverified', False)], default='unverified', max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('show_visitors', models.CharField(choices=[('yes', True), ('No', False)], default='No', max_length=50)),
                ('visitors_selected_block', models.CharField(default='block-1', max_length=100)),
                ('visitors_selected_days', models.CharField(choices=[(10, 'Last 10 days'), (20, 'Last 20 days'), (30, 'Last 30 days'), (60, 'Last 60 days'), (90, 'Last 90 days'), (180, 'Last 180 days'), (240, 'Last 240 days'), (365, 'Last 365 days')], default=10, max_length=100)),
                ('show_tickets', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('tickets_selected_block', models.CharField(default='block-1', max_length=100)),
                ('tickets_selected_days', models.CharField(choices=[(10, 'Last 10 days'), (20, 'Last 20 days'), (30, 'Last 30 days'), (60, 'Last 60 days'), (90, 'Last 90 days'), (180, 'Last 180 days'), (240, 'Last 240 days'), (365, 'Last 365 days')], default=10, max_length=100)),
                ('show_event', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('event_selected_block', models.CharField(default='block-1', max_length=100)),
                ('event_selected_days', models.CharField(choices=[(10, 'Last 10 days'), (20, 'Last 20 days'), (30, 'Last 30 days'), (60, 'Last 60 days'), (90, 'Last 90 days'), (180, 'Last 180 days'), (240, 'Last 240 days'), (365, 'Last 365 days')], default=10, max_length=100)),
                ('show_amenties', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('show_elevator', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('show_maintenances', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('maintenances_selected_block', models.CharField(default='block-1', max_length=100)),
                ('maintenances_selected_days', models.CharField(choices=[(10, 'Last 10 days'), (20, 'Last 20 days'), (30, 'Last 30 days'), (60, 'Last 60 days'), (90, 'Last 90 days'), (180, 'Last 180 days'), (240, 'Last 240 days'), (365, 'Last 365 days')], default=10, max_length=100)),
                ('show_attendance', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('attendance_selected_block', models.CharField(default='block-1', max_length=100)),
                ('attendance_selected_days', models.CharField(choices=[(10, 'Last 10 days'), (20, 'Last 20 days'), (30, 'Last 30 days'), (60, 'Last 60 days'), (90, 'Last 90 days'), (180, 'Last 180 days'), (240, 'Last 240 days'), (365, 'Last 365 days')], default=10, max_length=100)),
                ('cctv', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('cctv_selected_days', models.CharField(choices=[(10, 'Last 10 days'), (20, 'Last 20 days'), (30, 'Last 30 days'), (60, 'Last 60 days'), (90, 'Last 90 days'), (180, 'Last 180 days'), (240, 'Last 240 days'), (365, 'Last 365 days')], default=10, max_length=100)),
                ('cctv_live_or_not', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('show_housevacant', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('housevacant_selected_block', models.CharField(default='block-1', max_length=100)),
                ('show_guesthousevacant', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('guesthousevacant_selected_block', models.CharField(default='block-1', max_length=100)),
                ('show_alert_and_sos', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('alert_and_sos_selected_block', models.CharField(default='block-1', max_length=100)),
                ('show_medical_struck', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('medical_struck_selected_block', models.CharField(default='block-1', max_length=100)),
                ('show_residence_details', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('residence_selected_block', models.CharField(default='block-1', max_length=100)),
                ('show_inventory', models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=50)),
                ('inventory_selected_block', models.CharField(default='block-1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='app_details',
            fields=[
                ('apartment_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('apartment_name', models.CharField(max_length=100)),
                ('apartment_code', models.IntegerField(unique=True)),
                ('apartment_mail', models.EmailField(max_length=254, unique=True)),
                ('apartment_phn', models.BigIntegerField(unique=True)),
                ('apartment_descriptions', models.CharField(max_length=200)),
                ('apartment_address', models.CharField(max_length=250)),
                ('no_of_block', models.PositiveIntegerField()),
                ('no_of_flats', models.PositiveIntegerField()),
                ('no_of_elevator', models.PositiveIntegerField()),
                ('no_of_incharge', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='master_user',
            fields=[
                ('emp_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_emailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
